name: C Calculator CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Download repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Check compiler
      - name: Check GCC
        run: gcc --version

      # Step 3: Check Make
      - name: Check Make
        run: make --version

      # Step 4: Compile main application
      - name: Compile Application
        run: make all

      # Step 5: Run test suite
      - name: Run Test Cases
        run: make test

      # Step 6: Clean generated files
      - name: Clean
        run: make clean